version: "3.9"
services:
  db:
    image: "postgres:10.11"
    container_name: db
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    restart: always
    expose: ["5432"]
    volumes:
      - db-data:/var/lib/postgresql/data

  rails-app:
    build:
      context: ./app_e0
    container_name: rails-app
    ports: ["3000:3000"]
    depends_on:
      - db
    restart: unless-stopped
    links:
      - db:db

  sub-broker:
    build: .
    container_name: sub-broker
    depends_on:
      - db
    links:
      - db:db

  workers:
    build:
      context: ./workers
    container_name: workers
    ports: ["8080:8080"]

  redis-service:
    image: "redis:7.0.5"
    container_name: redis-service
    restart: always
    ports: ["6379:6379"]

volumes:
  db-data: