default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e0_app_development
  host: <%= ENV["DB_HOST"] %>
  port: 5432
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: e0_app_test
  host: <%= ENV["DB_HOST"] %>
  port: 5432
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

production:
  <<: *default
  database: e0_app_production
  host: <%= ENV["DB_HOST"] %>
  port: 5432
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>