name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag proyecto-base-grupo-26:$(date +%s)

    - uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: echo "hello world"
